#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri May 15 17:07:54 CST 2026
allowUnknownShaders=true
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=8
shaderPack=Solas Shader V3.5.zip
